language: python
python:
  - "3.5"
cache: pip
env: DJANGO_SETTINGS_MODULE="purebeurreV2.travis"
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations food_and_search
  - python manage.py migrate
  - python manage.py test
